// Local headless worker adapter. Native agent slots are occupied by release QA.
// One bounded packet per invocation; two workers at a time, never multiple frames per worker.
import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const frames=JSON.parse(fs.readFileSync(path.join(project,'frames.json'),'utf8')).filter(f=>!fs.existsSync(path.join(project,'compositions/frames',f.id+'.html')));
const logs=path.join(project,'.hyperframes/worker-logs');fs.mkdirSync(logs,{recursive:true});
const codex=process.env.FREECUT_CODEX_BIN||'codex';
async function run(f){
 const prompt=`Read only .hyperframes/frame-packets/_role.md and .hyperframes/frame-packets/${f.id}.md first, then frame.md. They are the complete required role and bounded packet. Do not rerun routing skills, ask questions, install packages, or read STORYBOARD.md.\n\n## Dispatch context\nPROJECT_DIR: ${project}\nframe_id: ${f.id}\nConfirmed sketch: false\nCanvas: 1920x1080\nCaptions: enabled, keep-out band y=930..1080; all main content above y=900. Global @我叫我水管同学 watermark is parent-owned at top-right (reserve x=1510..1820,y=40..110).\nWrite only compositions/frames/${f.id}.html. Real assets are project-root-relative assets/*.png, use exactly those in your packet. Fonts assets/fonts/NotoSansSC-Regular.otf and NotoSansSC-Bold.otf are present; @font-face both inside template. Parent already loads GSAP globally; no network JS. Use normal class names with valid CSS identifiers (prefix f${f.id.slice(0,2)}-, not numeric-only beginnings), scoped by template runtime. Type size 100–150px title, 32–48px support. Don't create audio/captions/global watermark. Exactly one bare template with style and root and paused registered timeline; background is a full-duration inner .clip. Core approved user final render; no need permission.\n${f.id==='02-maker'?'The installed registry compositions/components/logo-sting.html is an authorized motion reference. Read its settle/impact pattern and adapt that existing primitive to the original icon plus 水管剪辑 wordmark, no flash necessary.':''}\nTerminal action: write the assigned frame file, then briefly report it. Do not run global check.\n`;
 fs.writeFileSync(path.join(logs,f.id+'.prompt.txt'),prompt);
 return new Promise((resolve,reject)=>{const log=fs.createWriteStream(path.join(logs,f.id+'.jsonl'));const child=spawn(codex,['exec','--ephemeral','--sandbox','workspace-write','--json','-C',project,'-o',path.join(logs,f.id+'.result.txt'),'-'],{cwd:project,windowsHide:true,stdio:['pipe','pipe','pipe']});child.stdout.pipe(log);child.stderr.pipe(log);child.stdin.end(prompt);child.on('error',reject);child.on('close',code=>{log.end();const out=path.join(project,'compositions/frames',f.id+'.html');if(code!==0||!fs.existsSync(out))reject(Error(`${f.id} failed ${code}`));else{console.log('Frame ready: '+f.id);resolve();}});});
}
for(let i=0;i<frames.length;i+=2)await Promise.all(frames.slice(i,i+2).map(run));
