import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const frames = [
  { id:'01-freedom', title:'让创作，自由一点', duration:7, blueprint:'kinetic-type-beats', type:'typography', phrases:['让创作，自由一点。','全部功能永久免费，导出没有水印。'], headline:['让创作','自由一点'], assets:['icon.png'], role:'Lead with the viewer value, free all editing features and clean exports.' },
  { id:'02-maker', title:'一个初中生的真实作品', duration:7, blueprint:'logo-assemble-lockup', type:'brand', phrases:['我是一名初中生。','使用 GPT 六和 Codex，做出了水管剪辑。'], headline:['一个初中生','把想法做成了真的'], assets:['icon.png'], role:'Introduce the maker and name the actual product.' },
  { id:'03-control', title:'关键帧，点一下就会', duration:8, blueprint:'device-surface-showcase', type:'product-demo', phrases:['关键帧，点一下就能记录。','在预览里，直接拖动、缩放、旋转。'], headline:['关键帧','点一下就会'], assets:['editor-keyframes-030.png','editor-transform-030.png'], role:'Prove accessible motion editing with real screenshots, never claim a recorded gesture.' },
  { id:'04-layout', title:'两种布局，一份灵感', duration:8, blueprint:'comparison-split', type:'product-demo', phrases:['电脑布局，手机风格，随时切换。','把常用工具摆在眼前，按自己的习惯创作。'], headline:['两种布局','一份灵感'], assets:['editor-030.png','mobile-030.png'], role:'Show the real desktop app desktop/mobile-style layout options, not native phone builds.' },
  { id:'05-tools', title:'灵感之外，工具到位', duration:10, blueprint:'grid-card-assemble', type:'features', phrases:['自动字幕、语音朗读，模型按需下载，本地运行。','还有原创音效、左右声道、蒙版和调色。'], headline:['想做的效果','慢慢变成日常'], assets:['editor-030.png'], role:'Show actual optional local AI and creative tools without universal model license claims.' },
  { id:'06-open', title:'一起，把它做得更好', duration:7, blueprint:'kinetic-type-beats', type:'community', phrases:['这是一个还在成长的开源项目。','欢迎下载试用，反馈问题，一起把它做得更好。'], headline:['开源，也开放','一起把它做得更好'], assets:['icon.png'], role:'Invite honest preview testing rather than implying mature Jianying parity.' },
  { id:'07-download', title:'现在，轮到你的灵感', duration:8, blueprint:'titlecard-reveal', type:'cta', phrases:['下载地址见简介，关注我叫水管同学。','爱发电自愿赞助，不影响任何功能。'], headline:['下载地址见简介','现在，轮到你的灵感'], assets:['icon.png'], role:'Give accurate download destination and creator support copy with no invented support URL.' },
];
for (const dir of ['assets/voice','assets/music','assets/raw-voice','capture/extracted','compositions/frames','renders','scripts','.hyperframes']) fs.mkdirSync(path.join(project,dir),{recursive:true});
fs.writeFileSync(path.join(project,'frames.json'),JSON.stringify(frames,null,2)+'\n');
fs.writeFileSync(path.join(project,'capture/extracted/tokens.json'),JSON.stringify({colors:['#091C19','#12332B','#F4F3E8','#78E4BC','#FF8D73','#C4C8FA'],fonts:[{family:'Microsoft YaHei',weights:[400,700]}]},null,2));
fs.copyFileSync(path.resolve(project,'../../resources/icon.png'),path.join(project,'assets/icon.png'));
fs.copyFileSync(path.join(project,'BRIEF.md'),path.join(project,'user_script.txt'));
fs.writeFileSync(path.join(project,'capture/extracted/asset-descriptions.md'),'# Local product source inventory\n\nAll product claims are drawn from BRIEF.md and the current open source application, not a scraped competitor page.\n\n- icon.png: original generated ceramic mint F icon, project code FreeCut.\n- editor-030.png: actual Windows app, desktop layout.\n- mobile-030.png: actual same desktop app, mobile-style layout (not a native phone release).\n- editor-keyframes-030.png: actual easy keyframe inspector.\n- editor-transform-030.png: actual direct manipulation selection state.\n');
let cursor=0;
fs.writeFileSync(path.join(project,'STORYBOARD.md'),`---\nformat: 1920x1080\nduration: 55s\nmessage: 一个初中生用 GPT-6 与 Codex 做的剪辑软件，值得你试一试。\narc: value → maker → proof → options → tools → community → download\naudience: B站创作者与学生创作者\nmode: autonomous\nmusic: original deterministic electronic instrumental\n---\n\n## Video direction\n\nThis video tells creators that a junior high student made a real, fully free editor worth trying with GPT-6 and Codex. Mint, dark ink and warm paper; original icon, real screenshots and large Chinese type. Every frame keeps all important content above y=930; narration captions occupy y=954..1020. Global @我叫水管同学 watermark is mounted by the parent at right=100px,y=40px for the entire film. Screenshots are authentic still captures, not reconstructed fake UI, with no invented native phone availability. Changes are decisive and seek-safe, followed by readable holds, never idle wobble. No skill review question: user explicitly authorized autonomous final rendering in BRIEF.\n\n` + frames.map((f,i)=>{const start=cursor;cursor+=f.duration;return `## Frame ${i+1} — ${f.title}\n\n- status: outline\n- src: compositions/frames/${f.id}.html\n- duration: ${f.duration}s\n- transition_in: cut\n- scene: ${f.title}\n- voiceover: ${f.phrases.join('')}\n- poster: 4s\n- blueprint: ${f.blueprint}\n- type: ${f.type}\n- asset_candidates: ${f.assets.map(a=>'assets/'+a).join(', ')}\n- narrativeRole: ${f.role}\n\n0.0–1.1s: Reveal the principal headline “${f.headline[0]}” with a crisp masked entrance and strong composition.\n1.1–3.3s: Land the supporting headline “${f.headline[1]}”; reveal the product evidence named in asset_candidates.\n3.3–${f.duration-1}s: On the narration's second thought, change a meaningful state: reveal next real screenshot or a proof label; do not move a merely decorative dot.\n${f.duration-1}–${f.duration}s: Hold the final readable proof. No exit animation because the next frame hard cuts.\n\nExact additional copy: ${i===0?'“全部功能永久免费”, “无水印导出”, “不设会员 · 不设付费解锁”.':i===1?'“水管剪辑”, “我叫水管同学出品”, “GPT-6 + Codex”; no OpenAI logo.':i===2?'“记录当前画面” and “拖动 · 缩放 · 旋转”; use both actual screenshots with deliberate switch.':i===3?'“电脑布局” and “手机风格布局”; both refer to this desktop app, do not invent a phone hardware mockup.':i===4?'“自动字幕 / 语音朗读”, “按需下载 · 本地运行”, “原创音效 / 左右声道”, “7 种蒙版 / 19 种原创调色”, small clear “部分模型有独立许可”.':i===5?'“预览版，持续改进中”, “开源 · 试用 · 反馈”; avoid fabricated stars/download statistics.':'“水管剪辑”, “B站 UID 390310418”, “GitHub / Watertube-bilibili/freecut-desktop”, “爱发电自愿赞助 · 不影响任何功能”; no QR code, no Afdian URL.'}\n\nMotion rules: waterfall-entry, dynamic-content-sequencing.\n\n`}).join(''));
fs.writeFileSync(path.join(project,'SCRIPT.md'),'# Chinese narration\n\nVoice: Microsoft Huihui Desktop, installed Windows system voice; local offline SAPI synthesis.\nSettings: rate 1, volume 100; separately synthesized clauses padded into measured 55-second scene slots.\nDirection: clear and warm, confident student maker; pronunciation GPT 六 / Codex, on-screen spelling GPT-6 + Codex.\n\n'+frames.map((f,i)=>`## Line ${i+1} — ${f.title} (Frame ${i+1})\n\n**Delivery:** ${f.duration}s scene with concise spoken clauses and a readable hold.\n\n    ${f.phrases.join('')}\n\n`).join(''));
const ps=`$ErrorActionPreference = 'Stop'\nAdd-Type -AssemblyName System.Speech\n$projectDir = Split-Path -Parent $PSScriptRoot\n$items = Get-Content -LiteralPath (Join-Path $projectDir 'frames.json') -Raw -Encoding UTF8 | ConvertFrom-Json\n$speaker = New-Object System.Speech.Synthesis.SpeechSynthesizer\n$speaker.SelectVoice('Microsoft Huihui Desktop')\n$speaker.Rate = 1\n$speaker.Volume = 100\nforeach ($item in $items) {\n  for ($phraseIndex=0; $phraseIndex -lt $item.phrases.Count; $phraseIndex++) {\n    $wave = Join-Path $projectDir ('assets/raw-voice/' + $item.id + '-' + $phraseIndex + '.wav')\n    $speaker.SetOutputToWaveFile($wave)\n    $speaker.Speak([string]$item.phrases[$phraseIndex])\n    $speaker.SetOutputToNull()\n  }\n}\n$speaker.Dispose()\nWrite-Output 'Local SAPI narration created.'\n`;
fs.writeFileSync(path.join(project,'scripts/create-voice.ps1'),'\ufeff'+ps);
console.log('Prepared 7 scenes, 55 seconds, source files and local SAPI script.');
