import type { Effects } from '../types';
export interface EffectPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  swatch: string;
  values: Partial<Effects>;
}
const presets: EffectPreset[] = [
  {
    id: 'clean',
    name: '清透',
    category: '调色',
    description: '明亮通透的日常画面',
    swatch: '#94c8b8',
    values: { brightness: 1.08, contrast: 1.05, saturation: 1.08 },
  },
  {
    id: 'cinema',
    name: '电影青橙',
    category: '调色',
    description: '暖色调与柔和暗角',
    swatch: '#b58d61',
    values: { contrast: 1.18, saturation: 0.82, sepia: 0.22, vignette: 0.35 },
  },
  {
    id: 'film',
    name: '复古胶片',
    category: '调色',
    description: '褪色暖调，柔和对比',
    swatch: '#c79c72',
    values: { sepia: 0.48, contrast: 0.9, saturation: 0.78, brightness: 1.07 },
  },
  {
    id: 'mono',
    name: '经典黑白',
    category: '调色',
    description: '黑白画面与更深的对比',
    swatch: '#a5acac',
    values: { grayscale: 1, contrast: 1.2 },
  },
  {
    id: 'cold',
    name: '冷调夜色',
    category: '调色',
    description: '降低饱和度，偏移色相',
    swatch: '#658aaf',
    values: { hue: 15, saturation: 0.72, brightness: 0.92, contrast: 1.12 },
  },
  {
    id: 'warm',
    name: '落日暖光',
    category: '调色',
    description: '温暖明亮的金色氛围',
    swatch: '#d99a54',
    values: { sepia: 0.3, saturation: 1.3, brightness: 1.05 },
  },
  {
    id: 'pop',
    name: '鲜明',
    category: '调色',
    description: '高饱和与鲜明对比',
    swatch: '#c17485',
    values: { saturation: 1.6, contrast: 1.12 },
  },
  {
    id: 'soft',
    name: '柔焦',
    category: '画面',
    description: '轻微模糊并提亮画面',
    swatch: '#a4ada8',
    values: { blur: 2, brightness: 1.08, contrast: 0.9 },
  },
  {
    id: 'blur',
    name: '高斯模糊',
    category: '画面',
    description: '模糊当前图层，支持蒙版',
    swatch: '#8d999c',
    values: { blur: 12 },
  },
  {
    id: 'pixel',
    name: '像素化',
    category: '画面',
    description: '可调强度的马赛克效果',
    swatch: '#818795',
    values: { pixelate: 16 },
  },
  {
    id: 'vignette',
    name: '暗角',
    category: '画面',
    description: '聚焦中央主体',
    swatch: '#55615c',
    values: { vignette: 0.65 },
  },
  {
    id: 'green',
    name: '绿幕抠像',
    category: '抠像',
    description: '移除绿色背景，可调容差',
    swatch: '#68ad77',
    values: { chroma: true, chromaColor: '#00ff00', chromaThreshold: 100 },
  },
  {
    id: 'blue',
    name: '蓝幕抠像',
    category: '抠像',
    description: '移除蓝色背景，可调容差',
    swatch: '#657fc0',
    values: { chroma: true, chromaColor: '#0000ff', chromaThreshold: 100 },
  },
  {
    id: 'circle',
    name: '圆形蒙版',
    category: '蒙版',
    description: '将当前图层裁为圆形',
    swatch: '#92aaa2',
    values: { mask: 'circle', maskSize: 0.9 },
  },
  {
    id: 'rect',
    name: '矩形蒙版',
    category: '蒙版',
    description: '可调大小的矩形裁切',
    swatch: '#b9a281',
    values: { mask: 'rectangle', maskSize: 0.7 },
  },
  {
    id: 'mirror',
    name: '水平镜像',
    category: '画面',
    description: '水平翻转当前图层',
    swatch: '#91a8b8',
    values: { flipX: true },
  },
];

const additionalColors: EffectPreset[] = [
  {
    id: 'daylight',
    name: '晴日',
    category: '调色',
    description: '适度提亮，保留自然色彩',
    swatch: '#b1c697',
    values: { brightness: 1.06, contrast: 1.02, saturation: 1.12 },
  },
  {
    id: 'mist',
    name: '薄雾',
    category: '调色',
    description: '低对比与柔和淡彩',
    swatch: '#afbdb4',
    values: { brightness: 1.12, contrast: 0.82, saturation: 0.78 },
  },
  {
    id: 'forest',
    name: '林间',
    category: '调色',
    description: '加深层次，让风景更鲜明',
    swatch: '#55745a',
    values: { brightness: 0.98, contrast: 1.15, saturation: 1.35, vignette: 0.15 },
  },
  {
    id: 'coast',
    name: '海岸',
    category: '调色',
    description: '明亮通透的清凉画面',
    swatch: '#71a4ad',
    values: { brightness: 1.1, contrast: 1.08, saturation: 1.18, hue: 5 },
  },
  {
    id: 'amber',
    name: '琥珀',
    category: '调色',
    description: '偏暖的金褐色调',
    swatch: '#b5884d',
    values: { sepia: 0.4, saturation: 1.15, contrast: 1.08 },
  },
  {
    id: 'tea',
    name: '奶茶',
    category: '调色',
    description: '柔和明亮的浅暖色',
    swatch: '#c8b29b',
    values: { sepia: 0.18, brightness: 1.13, contrast: 0.9, saturation: 0.8 },
  },
  {
    id: 'faded',
    name: '旧日',
    category: '调色',
    description: '褪色低饱和的日常回忆',
    swatch: '#aa9c7c',
    values: { sepia: 0.2, saturation: 0.62, contrast: 0.88, brightness: 1.03, vignette: 0.18 },
  },
  {
    id: 'silver',
    name: '银盐',
    category: '调色',
    description: '明亮柔和的黑白灰阶',
    swatch: '#c2c5c6',
    values: { grayscale: 1, brightness: 1.08, contrast: 0.95 },
  },
  {
    id: 'ink',
    name: '墨影',
    category: '调色',
    description: '深黑和鲜明的明暗层次',
    swatch: '#41494e',
    values: { grayscale: 1, contrast: 1.45, brightness: 0.95, vignette: 0.3 },
  },
  {
    id: 'night',
    name: '深夜',
    category: '调色',
    description: '压低亮度并保留少量色彩',
    swatch: '#505878',
    values: { brightness: 0.8, contrast: 1.2, saturation: 0.55, hue: 10, vignette: 0.2 },
  },
  {
    id: 'candy',
    name: '糖果',
    category: '调色',
    description: '轻快明亮的丰富色彩',
    swatch: '#c48d9f',
    values: { brightness: 1.1, saturation: 1.45, contrast: 0.96 },
  },
  {
    id: 'documentary',
    name: '纪实',
    category: '调色',
    description: '克制饱和度，突出画面层次',
    swatch: '#898b74',
    values: { contrast: 1.12, saturation: 0.85, brightness: 1.02 },
  },
];
const additionalMasks: EffectPreset[] = [
  {
    id: 'ellipse-mask',
    name: '椭圆蒙版',
    category: '蒙版',
    description: '贴合横竖画幅的椭圆裁切',
    swatch: '#9cae9c',
    values: { mask: 'ellipse', maskSize: 0.8 },
  },
  {
    id: 'diamond-mask',
    name: '菱形蒙版',
    category: '蒙版',
    description: '四角菱形几何窗口',
    swatch: '#c5ad84',
    values: { mask: 'diamond', maskSize: 0.8 },
  },
  {
    id: 'star-mask',
    name: '星形蒙版',
    category: '蒙版',
    description: '五角星形状窗口',
    swatch: '#c4b67b',
    values: { mask: 'star', maskSize: 0.9 },
  },
  {
    id: 'heart-mask',
    name: '爱心蒙版',
    category: '蒙版',
    description: '柔和曲线的爱心窗口',
    swatch: '#bf9b9f',
    values: { mask: 'heart', maskSize: 0.9 },
  },
  {
    id: 'band-mask',
    name: '条带蒙版',
    category: '蒙版',
    description: '可旋转、移动的水平条带',
    swatch: '#91a3b6',
    values: { mask: 'band', maskSize: 1 },
  },
];
/** Color presets replace the previous grade so a prior monochrome look cannot stick. */
export const effectPresets: EffectPreset[] = [
  ...presets,
  ...additionalColors,
  ...additionalMasks,
].map((preset) => ({
  ...preset,
  values:
    preset.category === '调色'
      ? {
          brightness: 1,
          contrast: 1,
          saturation: 1,
          hue: 0,
          grayscale: 0,
          sepia: 0,
          vignette: 0,
          ...preset.values,
        }
      : preset.category === '蒙版'
        ? {
            maskX: 0,
            maskY: 0,
            maskRotation: 0,
            maskFeather: 0,
            maskInvert: false,
            ...preset.values,
          }
        : preset.values,
}));
